"""add web_sessions table

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-31 12:22:33.663198

Stage 6A independent-audit corrective pass #1 (still pre-acceptance, hence
amended directly rather than layering a repair migration on top — see
db/models.py's WebSession docstring for the full rationale of both changes
below):

- Blocker 1: created_at/expires_at/revoked_at are now `TIMESTAMP WITH TIME
  ZONE` (were plain naive `TIMESTAMP`), so the live expiry comparison in
  db/auth_sessions.py's get_active_sync() is an instant-vs-instant
  comparison, correct regardless of the PostgreSQL session's TimeZone GUC.
- Major 2: added an explicit `octet_length(session_token_hash) = 32` CHECK
  constraint — `sa.LargeBinary(length=32)` alone compiles to an
  unconstrained BYTEA on PostgreSQL and enforces nothing server-side.

Stage 6A independent-audit corrective pass #2, Major 1 (cookie-posture
session revival): added `issued_secure` (non-nullable boolean) — the
cookie posture (web_config.COOKIE_SECURE) a session was created under. See
db/models.py's WebSession docstring for the full rationale.

Stage 6A independent-audit corrective pass #3 (closing the remaining
creation/startup-transition race pass #2 left open): added
`web_session_policy`, a singleton table (`id` CHECK-constrained to exactly
1 — matching db/models.py's WEB_SESSION_POLICY_ID constant) holding the
ONE PostgreSQL-authoritative `current_secure` posture — see
db/models.py's WebSessionPolicy docstring for the full transactional
protocol this enables. Seeded with its one row (`current_secure = true`,
the fail-safe default) immediately after creation, in this same
migration — never lazily created by application code, which would reopen
exactly the kind of "two racing first-starts" question this whole pass
exists to eliminate. The literal `1` here is intentionally hardcoded
rather than imported from db/models.py — like every other migration in
this project (see 0001's own plain `sa.Column`/literal definitions), a
migration must remain a frozen, self-contained historical artifact,
never coupled to whatever db/models.py happens to say at replay time.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_sessions',
    sa.Column('session_token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issued_secure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('octet_length(session_token_hash) = 32', name=op.f('ck_web_sessions_session_token_hash_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_web_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('session_token_hash', name=op.f('pk_web_sessions'))
    )
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # web_session_policy: singleton authoritative posture row (Stage 6A
    # independent-audit corrective pass #3) — not autogenerated, hand-added
    # for the same reason web_sessions' own CHECK constraint above was.
    op.create_table(
        'web_session_policy',
        sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column('current_secure', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('id = 1', name=op.f('ck_web_session_policy_singleton_id')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_web_session_policy')),
    )
    # Seed the one and only row — fail-safe default (secure=true), matching
    # web_config.py's own COOKIE_SECURE default. Must happen here, in the
    # same migration that creates the table: application code never
    # lazily creates this row (see db/models.py's WebSessionPolicy
    # docstring for why that sidesteps a first-start race entirely).
    op.execute(sa.text("INSERT INTO web_session_policy (id, current_secure) VALUES (1, true)"))


def downgrade() -> None:
    op.drop_table('web_session_policy')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_sessions_user_id'), table_name='web_sessions')
    op.drop_table('web_sessions')
    # ### end Alembic commands ###
